name: spell-number
version: '0.1.0.0'
author: Stefano
maintainer: futtetennista@pm.me
extra-source-files:
- README.md
- stack.yaml
ghc-options:
- -Wall
- -fwarn-tabs
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates
# workaround [Filename case on macOS · Issue #4739 · haskell/cabal](https://github.com/haskell/cabal/issues/4739)
- -optP-Wno-nonportable-include-path
dependencies:
- base
- Cabal
- text
library:
  source-dirs: src/
  exposed-modules:
  - SpellNumber
executables:
  spell-number:
    main: Main.hs
    source-dirs: app/
    dependencies:
    - spell-number
tests:
  spell-number-test:
    main: Main.hs
    source-dirs: test/
    dependencies:
    - QuickCheck
    - spell-number
    - tasty
    - tasty-hunit
    - tasty-quickcheck
